#!/bin/bash

function update() {
  CURR_DIR=$(pwd)
  cd ~/git/
  for d in *
  do
    cd ~/git/$d
    echo -e "\e[0;32m~/git/$d:\e[0m"
    git pull
  done
  cd $CURR_DIR
}


function cm() {
  CURR_DIR=$(pwd)
  cd ~/catkin_ws/
  catkin_make -j2 -l2
  cd $CURR_DIR
}
